apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-nginx-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Mykematt/Argocd-plugin-test.git
    targetRevision: HEAD
    path: good-app
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
