steps:
  - label: "🤔 Step 3: Deploy Broken + Manual Decision"
    key: "deploy-broken-manual-decision"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#07b19cd:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "deploy"
          rollback_mode: "manual"
          timeout: 300
          health_check: true
          health_check_timeout: 120
          collect_logs: true
          upload_artifacts: true