steps:
  - label: "🔄 Step 5: Explicit Manual Rollback"
    key: "explicit-manual-rollback"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#d8743ec:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "rollback"
          rollback_mode: "manual"
          target_revision: "370"
          timeout: 300
          collect_logs: true
          upload_artifacts: true