steps:
  - label: "🔧 Step 4: Deploy Broken Version (health_check: false)"
    key: "deploy-broken-no-health-check"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#3a1f9ab:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "rollback"
          rollback_mode: "auto"
          collect_logs: true
          upload_artifacts: true
          log_lines: 2000
          notifications:
            slack_channel: "U08SQPXLH26"