steps:
  - label: "🔧 Step 4: Auto Rollback Test"
    key: "auto-rollback-test"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#aa5fef6:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "rollback"
          rollback_mode: "auto"
          collect_logs: true
          upload_artifacts: true
          log_lines: 2000
          notifications:
            slack_channel: "U08SQPXLH26"