steps:
  - label: "🚫 Step 3: Deploy Broken Version (manual rollback)"
    key: "deploy-broken-manual-rollback"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#840ce7b:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "deploy"
          rollback_mode: "manual"
          timeout: 600
          health_check_interval: 30
          health_check_timeout: 300
          notifications:
            slack_channel: "U08SQPXLH26"