steps:
  - label: "💥 Step 1: Deploy Working Version (auto-rollback)"
    key: "deploy-working-auto-rollback"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#d49c0ca:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "deploy"
          timeout: 600
          health_check_interval: 30
          health_check_timeout: 300
          notifications:
            slack_channel: "U08SQPXLH26"