steps:
  - label: "✅ Step 1: Deploy Good Version (establish baseline)"
    key: "deploy-good-baseline"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#aa5fef6:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "deploy"
          health_check_interval: 30
          health_check_timeout: 300
          notifications:
            slack_channel: "U08SQPXLH26"