agents:
  queue: kubernetes

steps:
  # Fetch secrets once for entire pipeline
  - label: "🔐 Fetch ArgoCD Secrets"
    key: "fetch-argocd-secrets"
    command: "echo '✅ ArgoCD secrets fetched for pipeline'"
    plugins:
      - secrets#v1.0.0:
          env:
            ARGOCD_PASSWORD: argocd_password

  - label: "🚀 Step 1: Deploy Baseline (Working Version)"
    depends_on: "fetch-argocd-secrets"
    plugins:
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#main:
          app: "test-nginx-app"
          argocd_server: "https://localhost:8080"
          argocd_username: "admin"
          # argocd_password now comes from environment variable
          mode: "deploy"
          timeout: 120
          health_check: true
          health_check_interval: 15
          health_check_timeout: 120
          notifications:
            slack_channel: "buildkite#ola-testing"
            email: "michael.omoge@buildkite.com"

  - label: "💥 Step 2: Deploy Broken Version (Auto-Rollback Test)"
    depends_on: "fetch-argocd-secrets"
    plugins:
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#main:
          app: "test-nginx-app-broken"
          argocd_server: "https://localhost:8080"
          argocd_username: "admin"
          # argocd_password now comes from environment variable
          mode: "deploy"
          timeout: 120
          health_check: true
          health_check_interval: 15
          health_check_timeout: 60
          notifications:
            slack_channel: "buildkite#ola-testing"
            email: "michael.omoge@buildkite.com"

  - label: "🚫 Step 3: Deploy Broken Version (No Auto-Rollback)"
    depends_on: "fetch-argocd-secrets"
    plugins:
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#main:
          app: "test-nginx-app-broken"
          argocd_server: "https://localhost:8080"
          argocd_username: "admin"
          # argocd_password now comes from environment variable
          mode: "deploy"
          timeout: 60
          health_check: false  # Disabled - no auto-rollback
          collect_logs: true
          log_lines: 1000
          upload_artifacts: true
          notifications:
            slack_channel: "buildkite#ola-testing"
            email: "michael.omoge@buildkite.com"

  - label: "🔄 Step 4: Manual Rollback"
    depends_on: "fetch-argocd-secrets"
    plugins:
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#main:
          app: "test-nginx-app-broken"
          argocd_server: "https://localhost:8080"
          argocd_username: "admin"
          # argocd_password now comes from environment variable
          mode: "rollback"
          rollback_mode: "manual"
          timeout: 120
          collect_logs: true
          log_lines: 1000
          upload_artifacts: true
          notifications:
            slack_channel: "buildkite#ola-testing"
            email: "michael.omoge@buildkite.com"
