steps:
  - label: "📦 Step 1: Deploy Good Baseline (main branch)"
    key: "deploy-good-baseline"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#8a0b344:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "deploy"
          timeout: 300
          collect_logs: true
          upload_artifacts: true