steps:
  - label: "🔧 Deploy Mode + Manual Rollback (Accept Failure)"
    key: "deploy-manual-rollback-test"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#00ec20a:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "rollback"
          rollback_mode: "manual"
          target_revision: "428"
          health_check_interval: 30
          health_check_timeout: 300
          collect_logs: true
          upload_artifacts: true
          log_lines: 2000
          notifications:
            slack_channel: "U08SQPXLH26"