steps:
  - label: "🔄 Step 4: Explicit Auto Rollback"
    key: "explicit-auto-rollback"
    agents:
      queue: kubernetes
    plugins:
      - secrets#v1.0.0:
          variables:
            ARGOCD_PASSWORD: argocd_password
      - github.com/Mykematt/argocd-deployment-buildkite-plugin#7acb6e8:
          app: "test-nginx-app"
          argocd_server: "argocd-server.argocd.svc.cluster.local:443"
          argocd_username: "admin"
          mode: "rollback"
          rollback_mode: "auto"
          timeout: 300
          collect_logs: true
          upload_artifacts: true